### ISSUE TITLE
Will this work with vite@5.x?

### ISSUE THREAD

**Issue by stevenpollack** [gebeto/storybook-addon-manual-mocks#14]
I'm using this with a project that relies on `vite: ^5` and I'm wondering if we can update the package.json to make `vite: ^4 || ^5` a peer dependency?

**Comment by gebeto** [comment]
I'm going to test it with `vite 5` and will let you know soon, also if it will be fine, I'll add v5 to peer deps

**Comment by stevenpollack** [comment]
any updates on this?

**Comment by stevenpollack** [comment]
Lovely! Thank you very much!

**Comment by gebeto** [comment]
Sure! Thanks for mentioned about vite v5, I didn't knew it was released 😄
