### ISSUE TITLE
Mocking uuid

### ISSUE THREAD

**Issue by sw-tracker** [gebeto/storybook-addon-manual-mocks#6]
Hi there,

I am trying to mock this import: `import { v4 as uuidv4 } from 'uuid';` (package.json dep: `"uuid": "9.0.0"`), but I am not able to.

I created a `uuid.ts` files with the following content: `export const v4 = () => 'some-uuuid';`.

I am using storybook 7.

Thanks!

**Comment by gebeto** [comment]
Hey 👋

This package only allow you to mock local packages(where used relative import `./`)

So if you want to mock `uuid` package, you can create your file `uuid.ts`, which will include `uuidv4` method:
```ts
import { v4 } from 'uuid';

export const uuidv4 = v4;
```

and then you can mock your `uuid.ts` file by creating `__mocks__/uuid.ts`:
```ts
export const uuidv4 = () => 'some-uuuid';
```

so your folder structure will be like this:
```
.
├── index.ts
├── uuid.ts
├── __mocks__
│   ├── uuid.ts
```

`index.ts` content is simple export of `uuid.ts`:
```ts
export * from './uuid';
```

---


After this, you can just import `uuid` from your component like this:
```ts
import { uuidv4 } from '../path/to/uuid';
```

**Comment by sw-tracker** [comment]
Thank you!

Can I override for a single story and/or component?

**Comment by gebeto** [comment]
Unfortunately now, but I have it in plans to add this feature later

**Comment by sw-tracker** [comment]
+1 for that feature :)
