### ISSUE TITLE
Ability to configure `MOCK_FOLDER` name

### ISSUE THREAD

**Issue by khanilov** [gebeto/storybook-addon-manual-mocks#7]
Hi 👋🏻 Your package looks promising!

How about adding option to change `MOCK_FOLDER` name?

In our project I would like to use `__storybook_mocks__` for example, because we have a lot of files in `__mocks__` folder for jest, that we are not always want to bring into storybook.

**Comment by gebeto** [comment]
v1 was released, and there are included ability to set custom mocks folder 🚀 Thanks for your suggection 🙌

Here is how to apply custom mocks folder path:
https://github.com/gebeto/storybook-addon-manual-mocks?tab=readme-ov-file#universal-config-for-vite-and-webpack

**Comment by khanilov** [comment]
Thank you!
